# Generated by Django 3.1.4 on 2021-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_title',
            new_name='doc_title',
        ),
    ]
